### ISSUE TITLE
Backup not created

### ISSUE THREAD

**Issue by AdamCatalyst** [DarkMatterCore/ww-43db-patcher#2]
I ran the app as a test, and found that no backup was created. To be sure, I ran it again. Same thing. Folder created, but no backup created.

p.s. I'd like to revert the change but I don't know how. Any help is greatly appreciated.

**Comment by Peter0x44** [comment]
Hi,
You can simply replace /slccmpt01/title/00000001/00000002/content/{0000001f.app, 00000022.app} with an unpatched one, using ftpiiueverywhere ***for cbhc***
USA consoles will have *1f.app
PAL consoles will have *22.app

I can't really think of why the file wouldn't be created, maybe the SD card write lock is on?
Why are you interested in reverting the change anyway?

**Comment by Peter0x44** [comment]
Well, it can now revert the patches on my fork.
Hopefully darkmattercore can give me feedback on it soon.

**Comment by DarkMatterCore** [comment]
Fixed in 52f2b4fa8af3ec302908ce7d1ad3236064700e57.
