### ISSUE TITLE
I have a error in ww-43db-patcher 

### ISSUE THREAD

**Issue by MarkuzKid** [DarkMatterCore/ww-43db-patcher#6]
![F44A5EC8-FA24-435A-A87D-F3BB351FCFFD](https://user-images.githubusercontent.com/88358397/127948817-94efed31-d0a2-4072-9a3c-4e8677507a68.jpeg)

I have this error.

**Comment by DarkMatterCore** [comment]
@MarkuzKid Hi there, mate. Please test this binary and send me another picture of the screen - this won't fix the issue, but it will fix the borked error message.

[boot.zip](https://github.com/DarkMatterCore/ww-43db-patcher/files/6920807/boot.zip)

**Comment by MarkuzKid** [comment]
I already fixed it by replacing the 0000001f.app, but thanks.
