### ISSUE TITLE
Request to add an option that will just patch WC24 Channels

### ISSUE THREAD

**Issue by Ingunar** [DarkMatterCore/ww-43db-patcher#7]
### The main reason why people use this patcher is to enable widescreen for these two titles:

- `HAJ` - Everybody Votes Channel
- `HAP` - Check Mii Out Channel

I feel that there is no real need to patch other WiiWare titles since they were made for 4:3 aspect ratio, but `HAJ` and `HAP` are 16:9 compatible. 

Could you add an option "Patch only WC24 channels" to overwrite IDs of these two by changing both `HAJ` and `HAP` to `HCB`?

That one worked for me without the problem, but ofc, any viable solution can be used.
My suggestion follows the ascending TitleID order without adding new TitleIDs to the list.
(`HCB` is 4:3-only so it really does not matter)

Patched IDs would look like this:
![FirstThreePatched](https://github.com/DarkMatterCore/ww-43db-patcher/assets/120290867/d5338681-7eaf-40b3-89ba-62d0a8d3f095)

**Comment by DarkMatterCore** [comment]
Sure, it can be done. Personally, I'd like to just patch all titles that \*do\* support a 16:9 aspect ratio, but verifying this in all regional ARDB files may prove to be very time-consuming.

**Comment by Ingunar** [comment]
Honestly, spent the better part of the last week testing and looking at YouTube videos for WW gameplay footage.
Even some disc titles from the 43DB that theoretically CAN look okayish in 16:9 and/or even have Home Menu 16:9 support are really 4:3. (Rayman Raving Rabbids 2 and TV Party)

Of course, I didn't check all of the WW titles, but based on what I've seen it is only two of those that are blocked by Nintendo on purpose. (Not sure why)

The Titles AND the Home menu can read the 4:3/16:9 flag from the System settings, but the 43DB only exists so WiiU can set the correct viewport.

The 43DB is only used to change the viewport before the title loads, or when the title loads.
(Still not sure when the call is made and what triggers it, but might be by SM before it boots the title)
The WW title will still load in 16:9 if it supports it, no matter how the viewport was set by the DMCU.

**Comment by DarkMatterCore** [comment]
@Ingunar Feel free to check f3fa917cf8f98f39caa393b729fa254a198d2763 -- it's still untested, but I believe it should work. I don't own a Wii U, so I can't test myself.

Keep in mind 67332725bff4083e53344cd806b7ac571546e50e changed the way SHA-1 checksum calculation is handled, so if something unexpected occurs, we could most likely blame that.

**Comment by Ingunar** [comment]
Fails with: `ardbPatchDatabaseFromSystemMenuArchive: Failed to write U8 archive backup!`

PS. I will DM you on Discord, so you can easily send me a new build after you manage to fix it.
(I have some problems building it myself, long story... )

**Comment by DarkMatterCore** [comment]
Implemented in e9cd08a07c2f33a0cfe3cf878bdff7eefc266e8e.
